abbr l "lsd"
abbr ll "lsd -l"
abbr ls "lsd"
abbr vim "nvim"
abbr cd "z"
abbr cat "bat -p --no-pager"
abbr more "bat -p" 
abbr glo "git log --oneline --decorate"
abbr glol "git log --graph --pretty='%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%ar) %C(bold blue)<%an>%Creset'"
abbr dl "nvim ~/Documents/daily-log/daily-log.md"
abbr cl "cd ~/Documents/daily-log && git add daily-log.md && git commit -m '$(date '+%Y-%m-%d') update' && cd -"
abbr ninstall "nix profile install nixpkgs#$1"
abbr cleannix "nix store gc"
abbr updateprofile "nix profile upgrade '.*'"
