# font_family JetBrainsMono Nerd Font
# bold_font auto
# italic_font auto
# bold_italic_font auto
font_size 12.0
disable_ligatures never

# Use specific Nerd Font symbols
symbol_map U+E000-U+E00D,U+E010-U+E017,U+E020-U+E029,U+E030-U+E03E,U+E040-U+E044,U+E050-U+E059,U+E060-U+E067,U+E070-U+E075,U+E080-U+E085,U+E090-U+E099,U+E0A0-U+E0A3,U+E0B0-U+E0B3,U+E0B4-U+E0C8,U+E0CA,U+E0CC-U+E0D4,U+E200-U+E2A9,U+E300-U+E3E3,U+E5FA-U+E6B1,U+E700-U+E7C5,U+F000-U+F2E0,U+F300-U+F372,U+F400-U+F532,U+F0001-U+F1AF0 JetBrainsMono Nerd Font

# Use a specific font for symbols
# This covers the private use area where most Nerd Font icons live
symbol_map U+E000-U+E00A,U+EA60-U+EBEB,U+F000-U+F2E0 Symbols Nerd Font Mono

# Fix for Starship / lsd icons
symbol_map U+e000-U+e00a,U+ea60-U+ebeb,U+f000-U+f2e0,U+f300-U+f32f,U+f400-U+f4a9,U+f500-U+f8ff,U+f0001-U+f1af0 Symbols Nerd Font Mono

env LANG=en_US.UTF-8


# BEGIN_KITTY_FONTS
font_family      family='JetBrainsMono Nerd Font' postscript_name=JetBrainsMonoNF-Regular
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS
# Set opacity (0.0 is fully transparent, 1.0 is fully opaque)
background_opacity 0.8
#dynamic_background_opacity yes

tab_bar_style        powerline
tab_powerline_style  angled
tab_bar_edge         top
tab_bar_align        left
